### ISSUE TITLE
Research tooltip

### ISSUE THREAD

**Issue by Texas-Policy-Lab** [Texas-Policy-Lab/COVID19#26]
Research different ways to add a tooltip to ggplot. 

I think this will probably be possible, but I haven't ever done it before!

**Comment by connorrothschild** [comment]
Check out features/tooltip if you wanna see my progress; I first used plotly but the tooltips were ugly. I've since transitioned to ggiraph (girafe function) which seems pretty good so far. https://davidgohel.github.io/ggiraph/articles/offcran/shiny.html

The only problem I'm having is the geom_line isn't showing up.

**Comment by Texas-Policy-Lab** [comment]
* Added tooltip to states
* Fixed line not rendering issue


BUG: State -Deaths plot isn't showing for some reason

**Comment by Texas-Policy-Lab** [comment]
Fixed bug. USA data API changed.

**Comment by connorrothschild** [comment]
>     * Added tooltip to states
> 
>     * Fixed line not rendering issue
> 
> 
> BUG: State -Deaths plot isn't showing for some reason

Looks like `deaths` is filled with NA; `death` has data (only after WHO declared pandemic)?

EDIT: Actually I'm not sure... What is the difference between death and deaths? in the state dataframe

Replacing deaths with death outputs this: 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/13339581/77683834-08e8a380-6f67-11ea-822c-54c81a0fa934.png">

**Comment by Texas-Policy-Lab** [comment]
We want to use the deaths data, I have to delete death( I think it's from another dataset). Deaths is working for me since I updated the code. Did you pull the branch?

**Comment by connorrothschild** [comment]
Cool, working for me now!
