### ISSUE TITLE
Legend should update to 'counties', 'countries'

### ISSUE THREAD

**Issue by connorrothschild** [Texas-Policy-Lab/COVID19#31]
Right now, all fill legends are 'states.' I figure this is an easy fix (changing 'legend_lab' in function) but wanted to document it here.
<img width="616" alt="image" src="https://user-images.githubusercontent.com/13339581/77700652-9980ad00-6f82-11ea-99c0-429787cb1f61.png">

**Comment by Texas-Policy-Lab** [comment]
YES! I saw this yesterday. Fixed it on a branch, I think add_timelines.
