### ISSUE TITLE
Add ggplots of testing data at the state level

### ISSUE THREAD

**Issue by Texas-Policy-Lab** [Texas-Policy-Lab/COVID19#6]

**Comment by connorrothschild** [comment]
@Texas-Policy-Lab do you have any tips on recommended reading for how make ggplot objects into functions?

I've been playing around with creating prototypes using the provided data, but I know that they aren't within the same format (everything is a function) as the rest of the project.

Should I just wrap the ggplot calls into a function (e.g. `draw_line_chart()`)?
